### ISSUE TITLE
ClassCastException on JmxNotification 

### ISSUE THREAD

**Issue by leleueri** [leleueri/argos#10]
With Cassandra 2.1 

[ERROR] [10/16/2016 04:02:45.720] [Argos-akka.actor.default-dispatcher-2479] [akka://Argos/user/SentinelOrchestrator/notification-jmx] [I cannot be cast to java.util.HashMap
java.lang.ClassCastException: [I cannot be cast to java.util.HashMap
        at io.argos.agent.sentinels.InternalNotificationsSentinel$$anonfun$processProtocolElement$1.applyOrElse(InternalNotificationsSentinel.scala:28)
        at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)
        at io.argos.agent.sentinels.Sentinel$$anonfun$receive$1.applyOrElse(Sentinel.scala:33)
        at akka.actor.Actor$class.aroundReceive(Actor.scala:484)
        at io.argos.agent.sentinels.Sentinel.aroundReceive(Sentinel.scala:22)
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)
        at akka.actor.ActorCell.invoke(ActorCell.scala:495)
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
        at akka.dispatch.Mailbox.run(Mailbox.scala:224)
        at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

**Comment by leleueri** [comment]
https://github.com/apache/cassandra/blob/81f6c784ce967fadb6ed7f58de1328e713eaf53c/src/java/org/apache/cassandra/utils/progress/jmx/JMXProgressSupport.java

https://github.com/apache/cassandra/blob/81f6c784ce967fadb6ed7f58de1328e713eaf53c/src/java/org/apache/cassandra/streaming/management/StreamEventJMXNotifier.java

https://github.com/apache/cassandra/blob/81f6c784ce967fadb6ed7f58de1328e713eaf53c/src/java/org/apache/cassandra/utils/progress/jmx/LegacyJMXProgressSupport.java
